py.install_sources(
     'acct_registered.py',
     'acme_register.py',
     'auth_hook.py',
     'auth_push_dns.py',
     'auth_push_http.py',
     'auth_push.py',
     'certbothook_data.py',
     'certbothook.py',
     'certbot.py',
     'cleanup_dns.py',
     'cleanup_hook.py',
     'cleanup_http.py',
     '__init__.py',
     'sign_cert.py',
     'sign_cert_wrap.py',
  subdir: 'ssl_mgr/cbot'
)
