#!/usr/bin/bash
#
# Source code checks.
#
# Run in top level directory
# 
mod='ssl_mgr'

echo "Python code"
cd ./src
PYTHONPATH=. pylint $mod/*.py $mod/*/*py

echo '   NB The following E741 for "O" can be ignored'
PYTHONPATH=. pycodestyle --max-line-length=110 $mod/*.py $mod/*/*py

mypy --check-untyped-defs --follow-untyped-imports $mod


