#!/usr/bin/bash
#
# Source code checks.
#
# Run in src dir
# i.e. cd src/gfw
# 

apps=(
    sslm-auth-hook.py
    sslm-cert-expiry.py
    sslm-cleanup-hook.py
    sslm-dhparm.py
    sslm-info.py
    sslm-mgr.py
    sslm-verify.py
)

modules=(
    app
    ca_sign
    cbot
    compare
    config
    config_service
    crypto_base
    crypto_cert
    crypto_csr
    crypto_dhparm
    crypto_hash
    db
    dns_base
    groups
    services
    tlsa
    utils
)
    
echo "-------------------------------"
echo "     pylint"
echo "-------------------------------"

PYTHONPATH=. pylint */*py ${apps[@]}


echo "-------------------------------"
echo "     pycodestyle"
echo "-------------------------------"

PYTHONPATH=. pycodestyle --max-line-length=110 */*py ${apps[@]}

echo "-------------------------------"
echo "     mypy"
echo "-------------------------------"

mypy --check-untyped-defs --follow-untyped-imports ${modules[@]} ${apps[@]}


