py.install_sources(
     'avail_services.py',
     'class_change.py',
     'class_tasks.py',
     'group_data.py',
     'group.py',
     'group_tasks.py',
     '__init__.py',
     'read_group.py',
     'tlsa_to_dns_serv.py',
     'tlsa_to_prod.py',
     'tlsa_update_domain.py',
  subdir: 'ssl_mgr/groups'
)
