py.install_sources(
     'class_cainfo.py',
     'class_opts.py',
     'conf_read.py',
     'dict_to_opts.py',
     '__init__.py',
     'opts_check.py',
     '_opts_data.py',
     'opts_parse.py',
     'opts.py',
     'renew_func_from_dict.py',
     'renew_info.py',
     'renew_target.py',
     'services_list.py',
     'version.py',
  subdir: 'ssl_mgr/config'
)
